<?php
/** @var Magento\Fremework\View\Element\Template $block */
/** @var Macademy\Blog\ViewModel\Post $postVm */
$postVm = $block->getData('post_vm');
?>
<div class="blog-post-sidebar">
    <p><strong><?= __('Other blog posts') ?></strong></p>
    <ul>
        <?php foreach($postVm->getList() as $post):?>
            <li>
                <a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getId()]) ?>">
                    <?= $post->getTitle() ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
